lemma = "majuna"
sitelenpona = [ "󱦢",]

[origin]
iso = "SP"
word = "maljuna"

[script]
kanata = "ᐊ"
anku = "아"
sewijen = ""
alapi = ""
kililisa = ""
elina = ""
tewanakali = ""
kijes = ""

[categories]
semantic = [ "descriptions",]

[definitions]
en = "old, aged, ancient"
