lemma = "ali"
sitelenpona = [ "󱤄",]

[origin]
iso = ""
word = ""

[script]
kanata = "ᐊᓕ"
anku = "아리"
sewijen = ""
alapi = ""
kililisa = ""
elina = ""
tewanakali = ""
kijes = ""

[categories]
semantic = [ "counting",]

[definitions]
en = "[pronunciation variant of ale]"
