lemma = "epiku"
sitelenpona = [ "󱦃",]

[origin]
iso = "FR"
word = "épique"

[script]
kanata = "ᐁᐱᑰ"
anku = "에피구"
sewijen = ""
alapi = ""
kililisa = ""
elina = ""
tewanakali = ""
kijes = ""

[categories]
semantic = [ "descriptions",]

[definitions]
en = "epic, cool, awesome, amazing"
