lemma = "lanpan"
sitelenpona = [ "󱦅",]

[origin]
iso = "GR"
word = "λαμβάνω"

[script]
kanata = "ᓚᓐᐸᓐ"
anku = "란판"
sewijen = ""
alapi = ""
kililisa = ""
elina = ""
tewanakali = ""
kijes = ""

[categories]
semantic = [ "activity",]

[definitions]
en = "take, seize, steal"
