lemma = "majuna"
sitelenpona = [ "󱦢",]

[origin]
iso = "SP"
word = "maljuna"

[script]
kanata = "ᒪᔫᓇ"
anku = "마유나"
sewijen = ""
alapi = ""
kililisa = ""
elina = ""
tewanakali = ""
kijes = ""

[categories]
semantic = [ "descriptions",]

[definitions]
en = "old, aged, ancient"
