lemma = "oko"
sitelenpona = [ "󱥺",]

[origin]
iso = "YU"
word = "око"

[script]
kanata = "ᐅᑯ"
anku = "오고"
sewijen = ""
alapi = ""
kililisa = ""
elina = ""
tewanakali = ""
kijes = ""

[categories]
semantic = [ "body",]

[definitions]
en = "see, look, view, examine, read, watch; visual; eye, seeing organ; (preverb) try to"
